Repository force-h2020/force-wfmanager, pull requests merged in 2020-01, with the labels that each got.

#336 Workflow mco_model attribute name change
  .travis.yml
  force_wfmanager/ui/setup/mco/tests/test_base_mco_options_view.py
  force_wfmanager/ui/setup/mco/tests/test_kpi_specification_view.py
  force_wfmanager/ui/setup/mco/tests/test_mco_parameter_view.py
  force_wfmanager/ui/setup/mco/tests/test_mco_view.py
  force_wfmanager/ui/setup/process/tests/test_data_source_view.py
  force_wfmanager/ui/setup/tests/test_setup_pane.py
  force_wfmanager/ui/setup/tests/test_workflow_tree.py
  force_wfmanager/ui/setup/tests/test_workflow_view.py
  force_wfmanager/ui/setup/tests/wfmanager_base_test_case.py
  force_wfmanager/ui/setup/workflow_tree.py
  force_wfmanager/ui/setup/workflow_view.py
  force_wfmanager/utils/tests/test_variable_names_registry.py
  force_wfmanager/utils/variable_names_registry.py
Labels: bdss compatibility

#338 FIX: Build status reference in README
  README.rst
Labels: bug

#340 FIX: New Workflow serialization / deserialization methods
  .travis.yml
  force_wfmanager/io/project_io.py
  force_wfmanager/io/workflow_io.py
  force_wfmanager/tests/test_wfmanager_review_task.py
  force_wfmanager/tests/test_wfmanager_setup_task.py
  force_wfmanager/tests/test_wfmanager_tasks.py
  force_wfmanager/ui/contributed_ui/contributed_ui.py
  force_wfmanager/ui/contributed_ui/tests/test_contributed_ui.py
  force_wfmanager/wfmanager_review_task.py
  force_wfmanager/wfmanager_setup_task.py
Labels: bug

#339 DEV: MCOEvent data display in the analysis pane
  force_wfmanager/server/event_deserializer.py
  force_wfmanager/tests/test_wfmanager_setup_task.py
  force_wfmanager/wfmanager_setup_task.py
Labels: enhancement, wip

#342 FIX: tests fix, removed the weights attribute
  force_wfmanager/server/tests/test_event_deserializer.py
  force_wfmanager/tests/test_wfmanager_setup_task.py
Labels: bug

#345 MAINT: Porting event serialization to BDSS
  force_wfmanager/notifications/tests/test_ui_notification.py
  force_wfmanager/notifications/ui_notification.py
  force_wfmanager/server/event_deserializer.py
  force_wfmanager/server/event_serializer.py
  force_wfmanager/server/tests/test_event_deserializer.py
  force_wfmanager/server/tests/test_event_serializer.py
  force_wfmanager/server/tests/test_zmq_server.py
  force_wfmanager/server/zmq_server.py
Labels: enhancement

#346 DEV: Reporting general type data values
  force_wfmanager/model/analysis_model.py
  force_wfmanager/model/tests/test_analysis_model.py
  force_wfmanager/notifications/ui_notification.py
  force_wfmanager/server/tests/test_zmq_server.py
  force_wfmanager/ui/review/plot.py
  force_wfmanager/ui/review/results_table.py
  force_wfmanager/ui/review/tests/test_plot.py
Labels: enhancement
